### ISSUE TITLE
2024 가을학기 추석 이벤트 홍보 모드 추가

### ISSUE THREAD

**Issue by ybmin** [sparcs-kaist/taxi-og-generator#22]
# Summary 

It implements ...

# Tasks 

- [x] 기본 OG image 변경 (2023 한가위 이벤트 코드 거의 그대로 활용합니다.)
- [x] 추천인 OG image 추가 (근간이 없습니다)

**Comment by kmc7468** [comment]
근간이 없다니... ㅋㅋㅋㅋ
